### ISSUE TITLE
embed-responsive only works with breakpoint prefix

### ISSUE THREAD

**Issue by jessSchn** [drdogbot7/tailwindcss-responsive-embed#8]
I'm using Tailwindcss 1.9.  I have "@tailwindcss/aspect-ratio": "^0.2.0",  "tailwindcss-responsive-embed": "^1.0.0" both installed.

My code looks like:
`<div class="iframe-area container md:mx-auto"><div class="iframe-wrapper embed-responsive aspect-w-4 aspect-h-3 md:aspect-w-16 md:aspect-h-9"><iframe src="http://yahoo.com" class="iframe-data embed-responsive-item " data-gtm-yt-inspected-40538660_18="true"></iframe></div></div>`

The embed-responsive looks like this for desktop sizes:
https://share.getcloudapp.com/GGuQJnkd

but the embed-responsive looks like this for mobile sizes:
https://share.getcloudapp.com/yAuDA7Y8

Even if I take the desktop (md:) out of my code my padding-bottom remains at 0px.  I'd like some guidance on how to get around this issue.

**Comment by drdogbot7** [comment]
Looks like you're using the [new aspect ratio utility](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) from @tailwindlabs. That didn't exist when this component was created, and it hasn't been tested with it.

In the meantime, try using [webdna/tailwindcss-aspect-ratio](https://github.com/webdna/tailwindcss-aspect-ratio)

```sh
npm install tailwindcss-aspect-ratio
```

**Comment by drdogbot7** [comment]
If you're using @tailwindcss/aspect-ratio, you don't need to use this component at all, b/c that utility _already_ does what this plugin does.

In this case, the reason it is breaking is that the `.embed-responsive` class sets `padding: 0;` by default, and it expects some kind of aspect ratio class **of greater specificity** to override that value. [webdna/tailwindcss-aspect-ratio](https://github.com/webdna/tailwindcss-aspect-ratio) does this, but [@tailwindcss/aspect-ratio](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) only achieves the necessary specificity when a specific breakpoint is used.

https://play.tailwindcss.com/lovQ2W3NxW?file=config

My recommendation is to ditch this plugin in favor of @tailwindcss/aspect-ratio.
